In [1]:
import numpy as np

In [2]:
import pandas as pd

In [16]:
data=pd.read_csv("car detail.csv")

In [17]:
data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [18]:
data.tail()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   object
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   object
 5   seller_type    8128 non-null   object
 6   transmission   8128 non-null   object
 7   owner          8128 non-null   object
 8   mileage        7907 non-null   object
 9   engine         7907 non-null   object
 10  max_power      7913 non-null   object
 11  torque         7906 non-null   object
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB

In [20]:
data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [21]:
data.dtypes

name              object
year               int64
selling_price      int64
km_driven          int64
fuel              object
seller_type       object
transmission      object
owner             object
mileage           object
engine            object
max_power         object
torque            object
seats            float64
dtype: object

In [30]:
data["mileage"] = data["mileage"].astype(str).str.extract(r"([\d.]+)", expand=False).astype(float)

data["engine"] = data["engine"].astype(str).str.extract(r"([\d.]+)", expand=False).astype(float)

data["max_power"] = data["max_power"].astype(str).str.extract(r"([\d.]+)", expand=False).astype(float)

In [38]:
#data = data.drop("torque", axis=1) for deleteing any features

In [40]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    data,
    test_size=0.2,
    random_state=42
)

In [45]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6502 entries, 6518 to 7270
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6502 non-null   object
 1   year           6502 non-null   int64
 2   selling_price  6502 non-null   int64
 3   km_driven      6502 non-null   int64
 4   fuel           6502 non-null   object
 5   seller_type    6502 non-null   object
 6   transmission   6502 non-null   object
 7   owner          6502 non-null   object
 8   mileage        6332 non-null   float64
 9   engine         6332 non-null   float64
 10  max_power      6335 non-null   float64
 11  seats          6332 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 660.4+ KB

In [46]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1626 entries, 1971 to 5428
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           1626 non-null   object
 1   year           1626 non-null   int64
 2   selling_price  1626 non-null   int64
 3   km_driven      1626 non-null   int64
 4   fuel           1626 non-null   object
 5   seller_type    1626 non-null   object
 6   transmission   1626 non-null   object
 7   owner          1626 non-null   object
 8   mileage        1575 non-null   float64
 9   engine         1575 non-null   float64
 10  max_power      1577 non-null   float64
 11  seats          1575 non-null   float64
dtypes: float64(4), int64(3), object(5)
memory usage: 165.1+ KB

In [48]:
X_train = train_data.drop("selling_price", axis=1)
y_train = train_data["selling_price"]

X_test = test_data.drop("selling_price", axis=1)
y_test = test_data["selling_price"]

In [50]:
num_cols = [
    "year",
    "km_driven",
    "mileage",
    "engine",
    "max_power",
    "seats"
]

cat_cols = [
    "fuel",
    "seller_type",
    "transmission",
    "owner"
]

In [52]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [54]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [58]:
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [67]:
#combining these two pipeline 
preprocessing = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

In [75]:
X_train_prepared = preprocessing.fit_transform(X_train)
X_test_prepared = preprocessing.fit_transform(X_test)

In [79]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [85]:
lin_reg.fit(X_train_prepared, y_train)

LinearRegression()

In [87]:
test_preds = lin_reg.predict(X_test_prepared)

In [89]:
from sklearn.metrics import mean_squared_error

test_rmse = mean_squared_error(y_test, test_preds) ** 0.5

print("Linear Regression Test RMSE:", test_rmse)

Linear Regression Test RMSE: 444643.62768148

In [91]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)

tree_reg.fit(X_train_prepared, y_train)

tree_preds = tree_reg.predict(X_test_prepared)

tree_rmse = mean_squared_error(y_test, tree_preds) ** 0.5

print("Decision Tree Test RMSE:", tree_rmse)

Decision Tree Test RMSE: 320772.9224251293

In [92]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(random_state=42)

tree_reg.fit(X_train_prepared, y_train)

tree_preds = tree_reg.predict(X_test_prepared)

tree_rmse = mean_squared_error(y_test, tree_preds) ** 0.5

print("Decision Tree Test RMSE:", tree_rmse)

Decision Tree Test RMSE: 320772.9224251293

In [95]:
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor(random_state=42)

forest_reg.fit(X_train_prepared, y_train)

tree_preds = forest_reg.predict(X_test_prepared)

forest_reg = mean_squared_error(y_test, tree_preds) ** 0.5

print("RandomForestRegressor:",forest_reg)

RandomForestRegressor: 182882.25112025143

In [97]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge()

ridge_reg.fit(X_train_prepared, y_train)

ridge_preds = ridge_reg.predict(X_test_prepared)

ridge_rmse = mean_squared_error(y_test, ridge_preds) ** 0.5

print("Ridge Test RMSE:", ridge_rmse)

Ridge Test RMSE: 445547.2104974294

In [103]:
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

svm_reg = SVR(kernel="rbf")

svm_reg.fit(X_train_prepared, y_train)

svm_preds = svm_reg.predict(X_test_prepared)

svm_rmse = mean_squared_error(y_test, svm_preds) ** 0.5

print("SVR Test RMSE:", svm_rmse)

SVR Test RMSE: 830698.7104129767

In [114]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(random_state=42)

forest_reg.fit(X_train_prepared, y_train)

RandomForestRegressor(random_state=42)

In [117]:
print(svm_reg)

[115844.18996447 234306.46344316 122099.45578192 129291.5602368
 124932.73902444 158753.7153206  147568.064599   132672.93492884
 163395.95834149 140784.42975019]

In [119]:
from sklearn.svm import SVR

svm_reg = SVR(kernel="rbf")

svm_reg.fit(X_train_prepared, y_train)

SVR()

In [121]:
from sklearn.model_selection import cross_val_score

svm_rmses = -cross_val_score(
    svm_reg,
    X_train_prepared,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=10
)

print("SVR CV RMSE:", svm_rmses)
print("Mean SVR CV RMSE:", svm_rmses.mean())

SVR CV RMSE: [810338.47208061 876490.99932618 899742.80089239 846356.94655459
 871612.28785968 681522.03813535 762998.3649705  946010.7523834
 756675.34971399 783821.5628945 ]
Mean SVR CV RMSE: 823556.9574811175

In [127]:
svm_test_preds = svm_reg.predict(X_test_prepared)

In [131]:
final_predictions = forest_reg.predict(X_test_prepared)

In [132]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": final_predictions
})

comparison.head(10)

   Actual Price  Predicted Price
0        198000    140584.990000
1        500000    575149.980000
2        425000    451399.890000
3        150000    192000.000000
4        525000    381874.960000
5        160000    191023.333333
6        450000    388499.960000
7        570000    680199.940000
8        170000    140890.000000
9        135000     72577.550000